CREATE DATABASE IF NOT EXISTS BANK_DB;

CREATE TABLE BANK_DB.PUBLIC.CUSTOMERS (
    ACCOUNT_NUMBER INT,
    CUSTOMER_NAME VARCHAR(100),
    ADDRESS VARCHAR(200),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    STATUS VARCHAR(20),
    BRANCH VARCHAR(50),
    AMOUNT NUMBER(15,2)
);


CREATE OR REPLACE PROCEDURE BANK_DB.PUBLIC.INSERT_CUSTOMER(
    P_ACCOUNT_NUMBER INT,
    P_CUSTOMER_NAME VARCHAR,
    P_ADDRESS VARCHAR,
    P_PHONE VARCHAR,
    P_EMAIL VARCHAR,
    P_STATUS VARCHAR,
    P_BRANCH VARCHAR,
    P_AMOUNT NUMBER(15,2)
)
RETURNS STRING
LANGUAGE SQL
AS
BEGIN
    INSERT INTO BANK_DB.PUBLIC.CUSTOMERS (ACCOUNT_NUMBER, CUSTOMER_NAME, ADDRESS, PHONE, EMAIL, STATUS, BRANCH, AMOUNT)
        VALUES (:P_ACCOUNT_NUMBER, :P_CUSTOMER_NAME, :P_ADDRESS, :P_PHONE, :P_EMAIL, :P_STATUS, :P_BRANCH, :P_AMOUNT);
    RETURN 'Customer inserted successfully';
END;


-- example call
CALL BANK_DB.PUBLIC.INSERT_CUSTOMER(1001, 'John Doe', '123 Main St', '9876543210', 'john@email.com', 'ACTIVE', 'Mumbai', 50000.00);



CALL BANK_DB.PUBLIC.INSERT_CUSTOMER(1002, 'Jane Smith', '456 Oak Ave', '9876543211', 'jane@email.com', 'ACTIVE', 'Delhi', 75000.00);
CALL BANK_DB.PUBLIC.INSERT_CUSTOMER(1003, 'Rahul Verma', '789 MG Road', '9876543212', 'rahul@email.com', 'ACTIVE', 'Bangalore', 120000.00);
CALL BANK_DB.PUBLIC.INSERT_CUSTOMER(1004, 'Priya Sharma', '12 Park St', '9876543213', 'priya@email.com', 'INACTIVE', 'Chennai', 30000.00);
CALL BANK_DB.PUBLIC.INSERT_CUSTOMER(1005, 'Amit Patel', '34 Lake View', '9876543214', 'amit@email.com', 'ACTIVE', 'Pune', 95000.00);
CALL BANK_DB.PUBLIC.INSERT_CUSTOMER(1006, 'Sneha Reddy', '56 Hill Road', '9876543215', 'sneha@email.com', 'ACTIVE', 'Hyderabad', 60000.00);

SELECT * FROM BANK_DB.PUBLIC.CUSTOMERS;


--check balance based on account number (if customer exists only, if not throw an error msg)
CREATE OR REPLACE PROCEDURE BANK_DB.PUBLIC.CHECK_BALANCE(P_ACCOUNT_NUMBER INT)
RETURNS STRING
LANGUAGE SQL
AS
DECLARE
    V_AMOUNT NUMBER(15,2);
    V_NAME VARCHAR;
BEGIN
    SELECT AMOUNT, CUSTOMER_NAME INTO :V_AMOUNT, :V_NAME
        FROM BANK_DB.PUBLIC.CUSTOMERS WHERE ACCOUNT_NUMBER = :P_ACCOUNT_NUMBER;

    IF (V_AMOUNT IS NULL) THEN
        RETURN 'Error: Customer with account number ' || :P_ACCOUNT_NUMBER || ' not found';
    END IF;

    RETURN 'Customer: ' || :V_NAME || ' | Balance: ' || :V_AMOUNT;
EXCEPTION
    WHEN OTHER THEN
        RETURN 'Error: Customer with account number ' || :P_ACCOUNT_NUMBER || ' not found';
END;


CALL BANK_DB.PUBLIC.CHECK_BALANCE(1001);
CALL BANK_DB.PUBLIC.CHECK_BALANCE(9999);




----------

--Deposit amount based on account number (if customer exists only, if not throw an error msg)
CREATE OR REPLACE PROCEDURE BANK_DB.PUBLIC.DEPOSIT(P_ACCOUNT_NUMBER INT, P_AMOUNT NUMBER(15,2))
RETURNS STRING
LANGUAGE SQL
AS
DECLARE
    V_COUNT INT;
    V_NEW_BALANCE NUMBER(15,2);
BEGIN
    SELECT COUNT(*) INTO :V_COUNT
        FROM BANK_DB.PUBLIC.CUSTOMERS WHERE ACCOUNT_NUMBER = :P_ACCOUNT_NUMBER;

    IF (V_COUNT = 0) THEN
        RETURN 'Error: Customer with account number ' || :P_ACCOUNT_NUMBER || ' not found';
    END IF;

    UPDATE BANK_DB.PUBLIC.CUSTOMERS
        SET AMOUNT = AMOUNT + :P_AMOUNT
        WHERE ACCOUNT_NUMBER = :P_ACCOUNT_NUMBER;

    SELECT AMOUNT INTO :V_NEW_BALANCE
        FROM BANK_DB.PUBLIC.CUSTOMERS WHERE ACCOUNT_NUMBER = :P_ACCOUNT_NUMBER;

    RETURN 'Deposit successful. New balance: ' || :V_NEW_BALANCE;
END;


CALL BANK_DB.PUBLIC.DEPOSIT(1001, 5000.00);
CALL BANK_DB.PUBLIC.DEPOSIT(9999, 1000.00);


--withdraw amount based on account number (if customer exists only, if not throw an error msg, check balance sufficient/insufficient)
CREATE OR REPLACE PROCEDURE BANK_DB.PUBLIC.WITHDRAW(P_ACCOUNT_NUMBER INT, P_AMOUNT NUMBER(15,2))
RETURNS STRING
LANGUAGE SQL
AS
DECLARE
    V_COUNT INT;
    V_BALANCE NUMBER(15,2);
    V_NEW_BALANCE NUMBER(15,2);
BEGIN
    SELECT COUNT(*) INTO :V_COUNT
        FROM BANK_DB.PUBLIC.CUSTOMERS WHERE ACCOUNT_NUMBER = :P_ACCOUNT_NUMBER;

    IF (V_COUNT = 0) THEN
        RETURN 'Error: Customer with account number ' || :P_ACCOUNT_NUMBER || ' not found';
    END IF;

    SELECT AMOUNT INTO :V_BALANCE
        FROM BANK_DB.PUBLIC.CUSTOMERS WHERE ACCOUNT_NUMBER = :P_ACCOUNT_NUMBER;

    IF (V_BALANCE < P_AMOUNT) THEN
        RETURN 'Error: Insufficient balance. Current balance: ' || :V_BALANCE;
    END IF;

    UPDATE BANK_DB.PUBLIC.CUSTOMERS
        SET AMOUNT = AMOUNT - :P_AMOUNT
        WHERE ACCOUNT_NUMBER = :P_ACCOUNT_NUMBER;

    SELECT AMOUNT INTO :V_NEW_BALANCE
        FROM BANK_DB.PUBLIC.CUSTOMERS WHERE ACCOUNT_NUMBER = :P_ACCOUNT_NUMBER;

    RETURN 'Withdrawal successful. New balance: ' || :V_NEW_BALANCE;
END;


CALL BANK_DB.PUBLIC.WITHDRAW(1001, 2000.00);
CALL BANK_DB.PUBLIC.WITHDRAW(1001, 999999.00);
CALL BANK_DB.PUBLIC.WITHDRAW(9999, 100.00);





--Display all customers based on branch using cursor (open, fetch, close)
CREATE OR REPLACE PROCEDURE BANK_DB.PUBLIC.GET_CUSTOMERS_BY_BRANCH(P_BRANCH VARCHAR)
RETURNS TABLE(ACCOUNT_NUMBER INT, CUSTOMER_NAME VARCHAR, ADDRESS VARCHAR, PHONE VARCHAR, EMAIL VARCHAR, STATUS VARCHAR, AMOUNT NUMBER(15,2))
LANGUAGE SQL
AS
DECLARE
    V_BRANCH VARCHAR DEFAULT P_BRANCH;
    RES RESULTSET;
BEGIN
    RES := (SELECT ACCOUNT_NUMBER, CUSTOMER_NAME, ADDRESS, PHONE, EMAIL, STATUS, AMOUNT
            FROM BANK_DB.PUBLIC.CUSTOMERS
            WHERE UPPER(BRANCH) = UPPER(:V_BRANCH));
    RETURN TABLE(RES);
END;


CALL BANK_DB.PUBLIC.GET_CUSTOMERS_BY_BRANCH('Mumbai');
CALL BANK_DB.PUBLIC.GET_CUSTOMERS_BY_BRANCH('Delhi');


select * from BANK_DB.PUBLIC.CUSTOMERS