CREATE DATABASE STREAMS ;

CREATE SCHEMA STREAMS.BRONZE ;

CREATE SCHEMA STREAMS.SILVER ;

CREATE SCHEMA STREAMS.GOLD ;

show schemas;

----creating table at bronze schema

CREATE OR REPLACE TABLE STREAMS.BRONZE.ORDERS (
    ORDER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR(50) NOT NULL,
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    SHIPPING_ADDRESS VARCHAR(500)
) ;

SELECT * FROM STREAMS.BRONZE.ORDERS ;


create or replace stream streams.bronze.orderstream
on table streams.bronze.orders append_only=false;
---query produced no results


----------------------------
---- SILVER LAYER: SCD TYPE 2 DIMENSION TABLE
----------------------------

CREATE OR REPLACE TABLE STREAMS.SILVER.ORDERS_SCD2 (
    ORDER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR(50) NOT NULL,
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    SHIPPING_ADDRESS VARCHAR(500),
    EFFECTIVE_FROM TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31'::TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE
);

----------------------------
---- INSERT INITIAL DATA INTO BRONZE
----------------------------

INSERT INTO STREAMS.BRONZE.ORDERS (CUSTOMER_ID, ORDER_DATE, ORDER_STATUS, TOTAL_AMOUNT, SHIPPING_ADDRESS)
VALUES
    (101, '2025-01-15', 'PENDING',   250.00, '123 Main St, New York, NY'),
    (102, '2025-01-16', 'SHIPPED',   450.75, '456 Oak Ave, Chicago, IL'),
    (103, '2025-01-17', 'DELIVERED', 1200.50, '789 Pine Rd, Denver, CO'),
    (104, '2025-01-18', 'PENDING',   320.00, '321 Elm St, Seattle, WA'),
    (105, '2025-01-19', 'CANCELLED',  89.99, '654 Maple Dr, Austin, TX');

SELECT * FROM STREAMS.BRONZE.ORDERS;

SELECT * FROM STREAMS.BRONZE.ORDERSTREAM;

----------------------------
---- TASK: MERGE STREAM INTO SILVER SCD TYPE 2
----------------------------

CREATE OR REPLACE TASK STREAMS.SILVER.ORDERS_SCD2_TASK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('STREAMS.BRONZE.ORDERSTREAM')
AS
MERGE INTO STREAMS.SILVER.ORDERS_SCD2 AS tgt
USING (
    SELECT
        ORDER_ID,
        CUSTOMER_ID,
        ORDER_DATE,
        ORDER_STATUS,
        TOTAL_AMOUNT,
        SHIPPING_ADDRESS,
        METADATA$ACTION,
        METADATA$ISUPDATE
    FROM STREAMS.BRONZE.ORDERSTREAM
) AS src
ON tgt.ORDER_ID = src.ORDER_ID AND tgt.IS_CURRENT = TRUE

WHEN MATCHED
    AND src.METADATA$ACTION = 'INSERT' AND src.METADATA$ISUPDATE = TRUE
THEN UPDATE SET
    tgt.IS_CURRENT    = FALSE,
    tgt.EFFECTIVE_TO  = CURRENT_TIMESTAMP()

WHEN NOT MATCHED
    AND src.METADATA$ACTION = 'INSERT'
THEN INSERT (ORDER_ID, CUSTOMER_ID, ORDER_DATE, ORDER_STATUS, TOTAL_AMOUNT, SHIPPING_ADDRESS, EFFECTIVE_FROM, EFFECTIVE_TO, IS_CURRENT)
     VALUES (src.ORDER_ID, src.CUSTOMER_ID, src.ORDER_DATE, src.ORDER_STATUS, src.TOTAL_AMOUNT, src.SHIPPING_ADDRESS, CURRENT_TIMESTAMP(), '9999-12-31'::TIMESTAMP_NTZ, TRUE);

----------------------------
---- TASK: INSERT NEW VERSION FOR UPDATED ROWS
----------------------------

CREATE OR REPLACE TASK STREAMS.SILVER.ORDERS_SCD2_INSERT_TASK
    WAREHOUSE = COMPUTE_WH
    AFTER STREAMS.SILVER.ORDERS_SCD2_TASK
AS
INSERT INTO STREAMS.SILVER.ORDERS_SCD2 (ORDER_ID, CUSTOMER_ID, ORDER_DATE, ORDER_STATUS, TOTAL_AMOUNT, SHIPPING_ADDRESS, EFFECTIVE_FROM, EFFECTIVE_TO, IS_CURRENT)
SELECT
    o.ORDER_ID,
    o.CUSTOMER_ID,
    o.ORDER_DATE,
    o.ORDER_STATUS,
    o.TOTAL_AMOUNT,
    o.SHIPPING_ADDRESS,
    CURRENT_TIMESTAMP(),
    '9999-12-31'::TIMESTAMP_NTZ,
    TRUE
FROM STREAMS.BRONZE.ORDERS o
INNER JOIN STREAMS.SILVER.ORDERS_SCD2 s
    ON o.ORDER_ID = s.ORDER_ID
    AND s.IS_CURRENT = FALSE
    AND s.EFFECTIVE_TO >= DATEADD('MINUTE', -2, CURRENT_TIMESTAMP())
WHERE NOT EXISTS (
    SELECT 1 FROM STREAMS.SILVER.ORDERS_SCD2 s2
    WHERE s2.ORDER_ID = o.ORDER_ID AND s2.IS_CURRENT = TRUE
);

----------------------------
---- RESUME TASKS
----------------------------

---- IMPORTANT: Resume child task FIRST, then root task
ALTER TASK IF EXISTS STREAMS.SILVER.ORDERS_SCD2_INSERT_TASK RESUME;
ALTER TASK STREAMS.SILVER.ORDERS_SCD2_TASK RESUME;

----------------------------
---- VERIFY: CHECK STREAM AND SILVER TABLE
----------------------------

SELECT * FROM STREAMS.BRONZE.ORDERSTREAM;


SELECT * FROM STREAMS.SILVER.ORDERS_SCD2 ORDER BY ORDER_ID, EFFECTIVE_FROM;

----------------------------
---- TEST SCD TYPE 2: UPDATE A ROW IN BRONZE
----------------------------

UPDATE STREAMS.BRONZE.ORDERS
SET ORDER_STATUS = 'SHIPPED', TOTAL_AMOUNT = 275.00
WHERE ORDER_ID = 1;

UPDATE STREAMS.BRONZE.ORDERS
SET ORDER_STATUS = 'DELIVERED'
WHERE ORDER_ID = 2;

SELECT * FROM STREAMS.BRONZE.ORDERSTREAM;

----------------------------
---- AFTER TASK RUNS, VERIFY SCD TYPE 2 HISTORY
----------------------------

SELECT * FROM STREAMS.SILVER.ORDERS_SCD2
ORDER BY ORDER_ID, EFFECTIVE_FROM;