CREATE DATABASE STREAMS ;

 

CREATE SCHEMA STREAMS.BRONZE ;

CREATE SCHEMA STREAMS.SILVER ;

CREATE SCHEMA STREAMS.GOLD ;

show schemas;

----creating table at bronze schema

CREATE OR REPLACE TABLE STREAMS.BRONZE.ORDERS (
    ORDER_ID NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR(50) NOT NULL,
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    SHIPPING_ADDRESS VARCHAR(500)
) ;

SELECT * FROM STREAMS.BRONZE.ORDERS ;

----------------------------
---- STREAM ON BRONZE TABLE
----------------------------

CREATE OR REPLACE STREAM STREAMS.BRONZE.ORDERSTREAM_SCD3
ON TABLE STREAMS.BRONZE.ORDERS APPEND_ONLY = FALSE;

----------------------------
---- INSERT INITIAL DATA INTO BRONZE
----------------------------

INSERT INTO STREAMS.BRONZE.ORDERS (CUSTOMER_ID, ORDER_DATE, ORDER_STATUS, TOTAL_AMOUNT, SHIPPING_ADDRESS)
VALUES
    (101, '2025-01-15', 'PENDING',   250.00, '123 Main St, New York, NY'),
    (102, '2025-01-16', 'SHIPPED',   450.75, '456 Oak Ave, Chicago, IL'),
    (103, '2025-01-17', 'DELIVERED', 1200.50, '789 Pine Rd, Denver, CO'),
    (104, '2025-01-18', 'PENDING',   320.00, '321 Elm St, Seattle, WA'),
    (105, '2025-01-19', 'CANCELLED',  89.99, '654 Maple Dr, Austin, TX');

SELECT * FROM STREAMS.BRONZE.ORDERS;

----------------------------
---- SILVER LAYER: SCD TYPE 3 DIMENSION TABLE
----------------------------

CREATE OR REPLACE TABLE STREAMS.SILVER.ORDERS_SCD3 (
    ORDER_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_STATUS VARCHAR(50) NOT NULL,
    PREVIOUS_ORDER_STATUS VARCHAR(50),
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    PREVIOUS_TOTAL_AMOUNT NUMBER(12,2),
    SHIPPING_ADDRESS VARCHAR(500),
    STATUS_CHANGED_DATE TIMESTAMP_NTZ,
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

----------------------------
---- TASK: MERGE STREAM INTO SILVER SCD TYPE 3
----------------------------

CREATE OR REPLACE TASK STREAMS.SILVER.ORDERS_SCD3_TASK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('STREAMS.BRONZE.ORDERSTREAM_SCD3')
AS
MERGE INTO STREAMS.SILVER.ORDERS_SCD3 AS tgt
USING (
    SELECT
        ORDER_ID,
        CUSTOMER_ID,
        ORDER_DATE,
        ORDER_STATUS,
        TOTAL_AMOUNT,
        SHIPPING_ADDRESS,
        METADATA$ACTION,
        METADATA$ISUPDATE
    FROM STREAMS.BRONZE.ORDERSTREAM_SCD3
    WHERE METADATA$ACTION = 'INSERT'
) AS src
ON tgt.ORDER_ID = src.ORDER_ID

WHEN MATCHED AND src.METADATA$ISUPDATE = TRUE
THEN UPDATE SET
    tgt.PREVIOUS_ORDER_STATUS  = tgt.ORDER_STATUS,
    tgt.PREVIOUS_TOTAL_AMOUNT  = tgt.TOTAL_AMOUNT,
    tgt.ORDER_STATUS           = src.ORDER_STATUS,
    tgt.TOTAL_AMOUNT           = src.TOTAL_AMOUNT,
    tgt.SHIPPING_ADDRESS       = src.SHIPPING_ADDRESS,
    tgt.STATUS_CHANGED_DATE    = CURRENT_TIMESTAMP(),
    tgt.LAST_UPDATED           = CURRENT_TIMESTAMP()

WHEN NOT MATCHED
THEN INSERT (ORDER_ID, CUSTOMER_ID, ORDER_DATE, ORDER_STATUS, PREVIOUS_ORDER_STATUS, TOTAL_AMOUNT, PREVIOUS_TOTAL_AMOUNT, SHIPPING_ADDRESS, STATUS_CHANGED_DATE, LAST_UPDATED)
     VALUES (src.ORDER_ID, src.CUSTOMER_ID, src.ORDER_DATE, src.ORDER_STATUS, NULL, src.TOTAL_AMOUNT, NULL, src.SHIPPING_ADDRESS, NULL, CURRENT_TIMESTAMP());

----------------------------
---- RESUME SCD3 TASK
----------------------------

ALTER TASK STREAMS.SILVER.ORDERS_SCD3_TASK RESUME;

----------------------------
---- VERIFY: CHECK SCD TYPE 3 TABLE (wait ~1-2 min for task to fire)
----------------------------

SELECT * FROM STREAMS.SILVER.ORDERS_SCD3 ORDER BY ORDER_ID;

----------------------------
---- TEST SCD TYPE 3: UPDATE ROWS IN BRONZE
----------------------------

UPDATE STREAMS.BRONZE.ORDERS
SET ORDER_STATUS = 'PROCESSING', TOTAL_AMOUNT = 300.00
WHERE ORDER_ID = 4;

UPDATE STREAMS.BRONZE.ORDERS
SET ORDER_STATUS = 'RETURNED'
WHERE ORDER_ID = 5;

SELECT * FROM STREAMS.BRONZE.ORDERSTREAM_SCD3;

----------------------------
---- AFTER TASK RUNS, VERIFY SCD TYPE 3 (previous values preserved)
----------------------------

SELECT * FROM STREAMS.SILVER.ORDERS_SCD3 ORDER BY ORDER_ID;